name: suside # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.3.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Suside Editor # 79 char long summary
description: |
  A code editor.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nodejs
